name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build_release:
    name: NIF ${{ matrix.nif }} - ${{ matrix.job.target }} (${{ matrix.job.os }})
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        nif: ["2.16"]
        job:
          - { target: aarch64-apple-darwin,      os: macos-14 }
          - { target: x86_64-apple-darwin,       os: macos-13 }
          - { target: aarch64-unknown-linux-gnu, os: ubuntu-22.04, use-cross: true }
          - { target: x86_64-unknown-linux-gnu,  os: ubuntu-22.04 }
          - { target: x86_64-unknown-linux-musl, os: ubuntu-22.04, use-cross: true }

    steps:
      - uses: actions/checkout@v4

      - uses: philss/rustler-precompiled-action@v1.1.4
        with:
          project-name: langelic_epub
          project-version: ${{ github.ref_name }}
          target: ${{ matrix.job.target }}
          nif-version: ${{ matrix.nif }}
          use-cross: ${{ matrix.job.use-cross || false }}
          project-dir: native/langelic_epub
